//
// Generated file, do not edit! Created by opp_msgc 4.4 from DynaPacket.msg.
//

#ifndef _DYNAPACKET_M_H_
#define _DYNAPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>DynaPacket.msg</tt> by opp_msgc.
 * <pre>
 * enum DynaPacketType
 * {
 *     DYNA_CONN_REQ = 0;
 *     DYNA_CONN_ACK = 1;
 *     DYNA_DISC_REQ = 2;
 *     DYNA_DISC_ACK = 3;
 *     DYNA_DATA = 4;
 * };
 * </pre>
 */
enum DynaPacketType {
    DYNA_CONN_REQ = 0,
    DYNA_CONN_ACK = 1,
    DYNA_DISC_REQ = 2,
    DYNA_DISC_ACK = 3,
    DYNA_DATA = 4
};

/**
 * Class generated from <tt>DynaPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet DynaPacket
 * {
 *     int srcAddress;
 *     int destAddress;
 *     int serverProcId;
 * };
 * </pre>
 */
class DynaPacket : public ::cPacket
{
  protected:
    int srcAddress_var;
    int destAddress_var;
    int serverProcId_var;

  private:
    void copy(const DynaPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DynaPacket&);

  public:
    DynaPacket(const char *name=NULL, int kind=0);
    DynaPacket(const DynaPacket& other);
    virtual ~DynaPacket();
    DynaPacket& operator=(const DynaPacket& other);
    virtual DynaPacket *dup() const {return new DynaPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcAddress() const;
    virtual void setSrcAddress(int srcAddress);
    virtual int getDestAddress() const;
    virtual void setDestAddress(int destAddress);
    virtual int getServerProcId() const;
    virtual void setServerProcId(int serverProcId);
};

inline void doPacking(cCommBuffer *b, DynaPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DynaPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>DynaPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet DynaDataPacket extends DynaPacket
 * {
 *     string payload;
 * };
 * </pre>
 */
class DynaDataPacket : public ::DynaPacket
{
  protected:
    opp_string payload_var;

  private:
    void copy(const DynaDataPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DynaDataPacket&);

  public:
    DynaDataPacket(const char *name=NULL, int kind=0);
    DynaDataPacket(const DynaDataPacket& other);
    virtual ~DynaDataPacket();
    DynaDataPacket& operator=(const DynaDataPacket& other);
    virtual DynaDataPacket *dup() const {return new DynaDataPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doPacking(cCommBuffer *b, DynaDataPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DynaDataPacket& obj) {obj.parsimUnpack(b);}


#endif // _DYNAPACKET_M_H_
