//
// Generated file, do not edit! Created by opp_msgc 4.4 from tictoc15.msg.
//

#ifndef _TICTOC15_M_H_
#define _TICTOC15_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>tictoc15.msg</tt> by opp_msgc.
 * <pre>
 * message TicTocMsg15
 * {
 *     int source;
 *     int destination;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class TicTocMsg15 : public ::cMessage
{
  protected:
    int source_var;
    int destination_var;
    int hopCount_var;

  private:
    void copy(const TicTocMsg15& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TicTocMsg15&);

  public:
    TicTocMsg15(const char *name=NULL, int kind=0);
    TicTocMsg15(const TicTocMsg15& other);
    virtual ~TicTocMsg15();
    TicTocMsg15& operator=(const TicTocMsg15& other);
    virtual TicTocMsg15 *dup() const {return new TicTocMsg15(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doPacking(cCommBuffer *b, TicTocMsg15& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TicTocMsg15& obj) {obj.parsimUnpack(b);}


#endif // _TICTOC15_M_H_
