//
// Generated file, do not edit! Created by opp_msgc 4.4 from routing/gpsr/GPSR.msg.
//

#ifndef _GPSR_M_H_
#define _GPSR_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "IPvXAddress.h"
#include "Coord.h"
#include "GPSRDefs.h"
// }}



/**
 * Class generated from <tt>routing/gpsr/GPSR.msg</tt> by opp_msgc.
 * <pre>
 * packet GPSRBeacon {
 *     IPvXAddress address;
 *     Coord position;
 * }
 * </pre>
 */
class GPSRBeacon : public ::cPacket
{
  protected:
    IPvXAddress address_var;
    Coord position_var;

  private:
    void copy(const GPSRBeacon& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GPSRBeacon&);

  public:
    GPSRBeacon(const char *name=NULL, int kind=0);
    GPSRBeacon(const GPSRBeacon& other);
    virtual ~GPSRBeacon();
    GPSRBeacon& operator=(const GPSRBeacon& other);
    virtual GPSRBeacon *dup() const {return new GPSRBeacon(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual IPvXAddress& getAddress();
    virtual const IPvXAddress& getAddress() const {return const_cast<GPSRBeacon*>(this)->getAddress();}
    virtual void setAddress(const IPvXAddress& address);
    virtual Coord& getPosition();
    virtual const Coord& getPosition() const {return const_cast<GPSRBeacon*>(this)->getPosition();}
    virtual void setPosition(const Coord& position);
};

inline void doPacking(cCommBuffer *b, GPSRBeacon& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GPSRBeacon& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>routing/gpsr/GPSR.msg</tt> by opp_msgc.
 * <pre>
 * packet GPSRPacket {
 *     GPSRForwardingMode routingMode;
 *     Coord destinationPosition;               
 *     Coord perimeterRoutingStartPosition;     
 *     Coord perimeterRoutingForwardPosition;   
 *     IPvXAddress currentFaceFirstSenderAddress;   
 *     IPvXAddress currentFaceFirstReceiverAddress; 
 *     IPvXAddress senderAddress; 
 * }
 * </pre>
 */
class GPSRPacket : public ::cPacket
{
  protected:
    GPSRForwardingMode routingMode_var;
    Coord destinationPosition_var;
    Coord perimeterRoutingStartPosition_var;
    Coord perimeterRoutingForwardPosition_var;
    IPvXAddress currentFaceFirstSenderAddress_var;
    IPvXAddress currentFaceFirstReceiverAddress_var;
    IPvXAddress senderAddress_var;

  private:
    void copy(const GPSRPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GPSRPacket&);

  public:
    GPSRPacket(const char *name=NULL, int kind=0);
    GPSRPacket(const GPSRPacket& other);
    virtual ~GPSRPacket();
    GPSRPacket& operator=(const GPSRPacket& other);
    virtual GPSRPacket *dup() const {return new GPSRPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual GPSRForwardingMode& getRoutingMode();
    virtual const GPSRForwardingMode& getRoutingMode() const {return const_cast<GPSRPacket*>(this)->getRoutingMode();}
    virtual void setRoutingMode(const GPSRForwardingMode& routingMode);
    virtual Coord& getDestinationPosition();
    virtual const Coord& getDestinationPosition() const {return const_cast<GPSRPacket*>(this)->getDestinationPosition();}
    virtual void setDestinationPosition(const Coord& destinationPosition);
    virtual Coord& getPerimeterRoutingStartPosition();
    virtual const Coord& getPerimeterRoutingStartPosition() const {return const_cast<GPSRPacket*>(this)->getPerimeterRoutingStartPosition();}
    virtual void setPerimeterRoutingStartPosition(const Coord& perimeterRoutingStartPosition);
    virtual Coord& getPerimeterRoutingForwardPosition();
    virtual const Coord& getPerimeterRoutingForwardPosition() const {return const_cast<GPSRPacket*>(this)->getPerimeterRoutingForwardPosition();}
    virtual void setPerimeterRoutingForwardPosition(const Coord& perimeterRoutingForwardPosition);
    virtual IPvXAddress& getCurrentFaceFirstSenderAddress();
    virtual const IPvXAddress& getCurrentFaceFirstSenderAddress() const {return const_cast<GPSRPacket*>(this)->getCurrentFaceFirstSenderAddress();}
    virtual void setCurrentFaceFirstSenderAddress(const IPvXAddress& currentFaceFirstSenderAddress);
    virtual IPvXAddress& getCurrentFaceFirstReceiverAddress();
    virtual const IPvXAddress& getCurrentFaceFirstReceiverAddress() const {return const_cast<GPSRPacket*>(this)->getCurrentFaceFirstReceiverAddress();}
    virtual void setCurrentFaceFirstReceiverAddress(const IPvXAddress& currentFaceFirstReceiverAddress);
    virtual IPvXAddress& getSenderAddress();
    virtual const IPvXAddress& getSenderAddress() const {return const_cast<GPSRPacket*>(this)->getSenderAddress();}
    virtual void setSenderAddress(const IPvXAddress& senderAddress);
};

inline void doPacking(cCommBuffer *b, GPSRPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GPSRPacket& obj) {obj.parsimUnpack(b);}


#endif // _GPSR_M_H_
